FROM mcr.microsoft.com/devcontainers/base:ubuntu
# Install the xz-utils package
RUN apt-get update && apt-get install -y zsh
RUN apt-get install -y r-base python3-pip python-is-python3
RUN apt-get install -y swig 
